const translations = {
  en: {
    header_subtitle:"Production-oriented AI, data and automation projects",
    vision_title:"Project Vision",
    vision_desc:"This portfolio showcases production-oriented AI and data products across language learning with Anki, RAG and conversational systems, forecasting, environmental monitoring and industrial automation. The projects cover complete workflows — from data pipelines and model evaluation to APIs, CI/CD, cloud deployment and user-facing applications.",
    top_title:"Top AI Products",
    top_subtitle:"The strongest product-focused projects, combining practical user workflows with modular AI architecture.",
    anki_title:"🧠 AI Anki Language Learning Suite",
    anki_desc:"A desktop AI application that turns vocabulary, grammar and real conversation practice into reviewed Anki learning materials.",
    anki_f1:"Complete vocabulary and grammar cards with quality validation",
    anki_f2:"Conversation practice with corrections, stronger answers and reusable expressions",
    anki_f3:"Batch / Queue import, duplicate-safe updates, Practice and Print Test",
    anki_f4:"Gemini, OpenAI and Claude plus optional ElevenLabs, OpenAI, Gemini and Piper TTS",
    rag_title:"💬 Anki RAG Conversation Tutor · In Development",
    rag_desc:"A cloud-ready conversational learning service that uses the learner's Anki deck as a personal knowledge base.",
    rag_f1:"FastAPI service with structured Pydantic contracts",
    rag_f2:"Semantic retrieval from Anki topics and vocabulary with Qdrant Cloud",
    rag_f3:"LangGraph orchestration for guided, context-aware practice",
    rag_f4:"Docker, testing, CI/CD and cloud deployment roadmap",
    data_title:"Data, ML & Cloud Projects",
    data_subtitle:"End-to-end analytical platforms with automated pipelines, tested domain logic and live deployments.",
    passengers_title:"✈️ Canary Islands Air Passenger Forecasting",
    passengers_desc:"Forecasting platform based on official Canary Islands passenger data. It combines XGBoost and LSTM models, feature engineering, KPI analysis, automated data ingestion, GitHub Actions CI and Streamlit Community Cloud deployment.",
    calima_title:"🌫️ Calima Detection & Air Quality Platform",
    calima_desc:"Cloud-deployed monitoring platform with hourly Open-Meteo ingestion, MongoDB and MongoEngine persistence, CQRS read/write separation, idempotent multi-hour event detection, pytest coverage, Docker and Render deployment.",
    next_title:"In Progress & Next Ideas",
    next_subtitle:"Projects that extend the portfolio ecosystem while the next concept remains intentionally under wraps.",
    traveller_title:"🌴 Canary AI Traveller · In Progress",
    traveller_desc:"An AI travel assistant for the Canary Islands combining destination data, environmental conditions and conversational trip planning with Django, SQL and LLM tooling.",
    surprise_title:"🔒 Surprise Project",
    surprise_desc:"A new project is already taking shape. Its concept, stack and scope will be revealed when the first working version is ready.",
    support_title:"Supporting Projects",
    support_desc:"Earlier systems, research tracks and technical exercises remain available as supporting evidence of continuous development.",
    event_desc:"A modular event platform with independent services and dedicated ML research tracks for recommendation, sentiment analysis and event classification.",
    research_title:"ML research within the platform",
    data_projects_title:"Data and engineering projects",
    rec_desc:"Benchmark of multiple models for recommendation-driven classification and consistent model selection.",
    sent_desc:"Sentiment experiments comparing classical ML baselines with Hugging Face transformers.",
    evt_desc:"Event classification research using an MLP baseline and reproducible training pipeline.",
    transaction_desc:"Python reporting project for CSV processing, cleaning, anomaly detection and automated summaries.",
    travel_desc:"SQL and Python project for travel-agency data processing, validation and querying.",
    subscription_desc:"OOP project using the Abstract Factory pattern with TXT and JSON formats.",
    about_title:"About me",
    about_desc:"I am a Data Scientist and AI Engineer with a background in computer vision, automation and industrial systems. I have worked in real production environments, analysing data, diagnosing system behaviour and building practical technical solutions. My current focus is applied AI, machine learning, RAG, agentic workflows and production-ready Python applications.",
    contact_title:"Contact",
    live:"Open live app",
    github:"GitHub",
    repo_soon:"Repository coming soon",
    coming_soon:"Coming soon",
    in_development:"In development",
    flagship:"Flagship product"
  },
  es: {
    header_subtitle:"Proyectos de IA, datos y automatización orientados a producción",
    vision_title:"Visión del proyecto",
    vision_desc:"Este portfolio presenta productos de IA y datos orientados a producción: aprendizaje de idiomas con Anki, sistemas RAG y conversacionales, forecasting, monitorización medioambiental y automatización industrial. Los proyectos cubren flujos completos, desde pipelines de datos y evaluación de modelos hasta APIs, CI/CD, despliegue cloud y aplicaciones para usuarios.",
    top_title:"Productos principales de IA",
    top_subtitle:"Los proyectos más orientados a producto, combinando flujos de usuario reales con una arquitectura de IA modular.",
    anki_title:"🧠 Suite de aprendizaje de idiomas con AI Anki",
    anki_desc:"Aplicación de escritorio que convierte vocabulario, gramática y práctica de conversación en materiales revisados para Anki.",
    anki_f1:"Tarjetas completas de vocabulario y gramática con validación de calidad",
    anki_f2:"Conversaciones con correcciones, respuestas mejoradas y expresiones reutilizables",
    anki_f3:"Importación Batch / Queue, actualización segura de duplicados, Practice y Print Test",
    anki_f4:"Gemini, OpenAI y Claude, con TTS opcional de ElevenLabs, OpenAI, Gemini y Piper",
    rag_title:"💬 Tutor conversacional RAG para Anki · En desarrollo",
    rag_desc:"Servicio conversacional preparado para cloud que utiliza el mazo de Anki del usuario como base de conocimiento personal.",
    rag_f1:"Servicio FastAPI con contratos estructurados en Pydantic",
    rag_f2:"Recuperación semántica de temas y vocabulario con Qdrant Cloud",
    rag_f3:"Orquestación con LangGraph para práctica guiada y contextual",
    rag_f4:"Docker, tests, CI/CD y hoja de ruta de despliegue cloud",
    data_title:"Proyectos de datos, ML y cloud",
    data_subtitle:"Plataformas analíticas end-to-end con pipelines automáticos, lógica de dominio probada y despliegues activos.",
    passengers_title:"✈️ Forecasting de pasajeros aéreos de Canarias",
    passengers_desc:"Plataforma de predicción basada en datos oficiales de pasajeros de Canarias. Combina XGBoost y LSTM, feature engineering, KPIs, ingestión automática, CI con GitHub Actions y despliegue en Streamlit Community Cloud.",
    calima_title:"🌫️ Plataforma de detección de calima y calidad del aire",
    calima_desc:"Plataforma desplegada en cloud con ingestión horaria desde Open-Meteo, persistencia MongoDB/MongoEngine, separación CQRS de lectura y escritura, detector idempotente de eventos, cobertura con pytest, Docker y Render.",
    next_title:"En progreso y próximas ideas",
    next_subtitle:"Proyectos que amplían el ecosistema del portfolio mientras el próximo concepto permanece deliberadamente en secreto.",
    traveller_title:"🌴 Canary AI Traveller · En progreso",
    traveller_desc:"Asistente de viajes con IA para Canarias que combina datos del destino, condiciones medioambientales y planificación conversacional mediante Django, SQL y herramientas LLM.",
    surprise_title:"🔒 Proyecto sorpresa",
    surprise_desc:"Ya está tomando forma un nuevo proyecto. Su concepto, stack y alcance se revelarán cuando exista una primera versión funcional.",
    support_title:"Proyectos complementarios",
    support_desc:"Los sistemas anteriores, líneas de research y ejercicios técnicos siguen disponibles como evidencia adicional de desarrollo continuo.",
    event_desc:"Plataforma modular de eventos con servicios independientes y líneas de research ML para recomendación, sentimiento y clasificación.",
    research_title:"Research ML dentro de la plataforma",
    data_projects_title:"Proyectos de datos e ingeniería",
    rec_desc:"Benchmark de varios modelos para clasificación basada en recomendaciones y selección consistente.",
    sent_desc:"Experimentos de sentimiento comparando ML clásico con transformers de Hugging Face.",
    evt_desc:"Investigación de clasificación de eventos con baseline MLP y pipeline reproducible.",
    transaction_desc:"Proyecto de reporting en Python para procesar CSV, limpiar datos, detectar anomalías y generar resúmenes.",
    travel_desc:"Proyecto SQL y Python para procesar, validar y consultar datos de una agencia de viajes.",
    subscription_desc:"Proyecto OOP con Abstract Factory y formatos TXT y JSON.",
    about_title:"Sobre mí",
    about_desc:"Soy Data Scientist e Ingeniera de IA con experiencia en visión por computador, automatización y sistemas industriales. He trabajado en entornos reales de producción, analizando datos, diagnosticando sistemas y creando soluciones técnicas prácticas. Actualmente me centro en IA aplicada, machine learning, RAG, flujos agentic y aplicaciones Python preparadas para producción.",
    contact_title:"Contacto",
    live:"Abrir aplicación",
    github:"GitHub",
    repo_soon:"Repositorio próximamente",
    coming_soon:"Próximamente",
    in_development:"En desarrollo",
    flagship:"Producto principal"
  },
  pl: {
    header_subtitle:"Produkcyjne projekty AI, data i automatyzacji",
    vision_title:"Wizja projektów",
    vision_desc:"Portfolio prezentuje praktyczne produkty AI i data: naukę języków z Anki, systemy RAG i konwersacyjne, prognozowanie, monitoring środowiskowy oraz automatyzację przemysłową. Projekty obejmują pełne workflow — od pipeline'ów danych i ewaluacji modeli po API, CI/CD, wdrożenia chmurowe i aplikacje dla użytkowników.",
    top_title:"Najważniejsze produkty AI",
    top_subtitle:"Najmocniejsze projekty produktowe, łączące realne potrzeby użytkownika z modularną architekturą AI.",
    anki_title:"🧠 AI Anki Language Learning Suite",
    anki_desc:"Desktopowa aplikacja AI, która zamienia słownictwo, gramatykę i prawdziwą praktykę konwersacji w sprawdzone materiały do Anki.",
    anki_f1:"Kompletne fiszki słownictwa i gramatyki z walidacją jakości",
    anki_f2:"Konwersacje z korektą, lepszą odpowiedzią i wyborem przydatnych wyrażeń",
    anki_f3:"Import Batch / Queue, bezpieczna aktualizacja duplikatów, Practice i Print Test",
    anki_f4:"Gemini, OpenAI i Claude oraz opcjonalne TTS: ElevenLabs, OpenAI, Gemini i Piper",
    rag_title:"💬 Anki RAG Conversation Tutor · W budowie",
    rag_desc:"Gotowy do wdrożenia w chmurze tutor konwersacyjny, który wykorzystuje talię Anki użytkownika jako prywatną bazę wiedzy.",
    rag_f1:"Serwis FastAPI ze strukturyzowanymi kontraktami Pydantic",
    rag_f2:"Semantyczne wyszukiwanie tematów i słownictwa w Qdrant Cloud",
    rag_f3:"Orkiestracja LangGraph dla prowadzonej praktyki w kontekście",
    rag_f4:"Docker, testy, CI/CD i plan wdrożenia chmurowego",
    data_title:"Projekty data, ML i cloud",
    data_subtitle:"Kompletne platformy analityczne z automatycznymi pipeline'ami, testowaną logiką domenową i działającymi wdrożeniami.",
    passengers_title:"✈️ Prognozowanie pasażerów lotniczych na Wyspach Kanaryjskich",
    passengers_desc:"Platforma forecastingowa oparta na oficjalnych danych pasażerskich. Łączy XGBoost i LSTM, feature engineering, analizę KPI, automatyczne pobieranie danych, CI w GitHub Actions i wdrożenie w Streamlit Community Cloud.",
    calima_title:"🌫️ Platforma wykrywania kalimy i jakości powietrza",
    calima_desc:"Platforma chmurowa z godzinnym pobieraniem danych Open-Meteo, bazą MongoDB/MongoEngine, rozdzieleniem odczytu i zapisu w CQRS, idempotentnym wykrywaniem zdarzeń wielogodzinnych, testami pytest, Dockerem i wdrożeniem na Render.",
    next_title:"W budowie i kolejne pomysły",
    next_subtitle:"Projekty rozwijające ekosystem portfolio, podczas gdy następny koncept celowo pozostaje tajemnicą.",
    traveller_title:"🌴 Canary AI Traveller · W trakcie",
    traveller_desc:"Asystent podróży po Wyspach Kanaryjskich łączący dane o kierunkach, warunki środowiskowe i konwersacyjne planowanie podróży w Django, SQL i narzędziach LLM.",
    surprise_title:"🔒 Projekt Surprise",
    surprise_desc:"Nowy projekt już nabiera kształtu. Jego pomysł, stack i zakres zostaną ujawnione dopiero wraz z pierwszą działającą wersją.",
    support_title:"Projekty uzupełniające",
    support_desc:"Wcześniejsze systemy, ścieżki badawcze i ćwiczenia techniczne pozostają jako dodatkowy dowód ciągłego rozwoju.",
    event_desc:"Modułowa platforma eventowa z niezależnymi usługami i osobnymi ścieżkami researchu ML dla rekomendacji, sentymentu i klasyfikacji.",
    research_title:"Research ML w ramach platformy",
    data_projects_title:"Projekty data i inżynieryjne",
    rec_desc:"Benchmark wielu modeli dla klasyfikacji opartej o rekomendacje i spójnego wyboru najlepszego podejścia.",
    sent_desc:"Eksperymenty sentymentu porównujące klasyczny ML z transformerami Hugging Face.",
    evt_desc:"Research klasyfikacji eventów z baseline'em MLP i powtarzalnym pipeline'em treningowym.",
    transaction_desc:"Projekt raportowy w Pythonie: CSV, czyszczenie danych, wykrywanie anomalii i automatyczne podsumowania.",
    travel_desc:"Projekt SQL i Python do przetwarzania, walidacji oraz odpytywania danych biura podróży.",
    subscription_desc:"Projekt OOP wykorzystujący Abstract Factory oraz formaty TXT i JSON.",
    about_title:"O mnie",
    about_desc:"Jestem Data Scientist i AI Engineer z doświadczeniem w computer vision, automatyzacji i systemach przemysłowych. Pracowałam w rzeczywistych środowiskach produkcyjnych, analizując dane, diagnozując zachowanie systemów i tworząc praktyczne rozwiązania techniczne. Obecnie skupiam się na applied AI, machine learningu, RAG, agentic workflows i produkcyjnych aplikacjach w Pythonie.",
    contact_title:"Kontakt",
    live:"Otwórz aplikację",
    github:"GitHub",
    repo_soon:"Repozytorium wkrótce",
    coming_soon:"Wkrótce",
    in_development:"W budowie",
    flagship:"Projekt flagowy"
  }
};
function setLang(lang){
  const selected=translations[lang]||translations.en;
  document.documentElement.lang=lang;
  document.querySelectorAll('[data-i18n]').forEach((el)=>{
    const key=el.dataset.i18n;
    if(selected[key]) el.textContent=selected[key];
  });
}
document.addEventListener('DOMContentLoaded',()=>setLang('en'));
